par n = [(x, y) | x <- [1 .. n], y <- [1 .. n]]
sm n = sum [(x * y) | x <- [1 .. n], y <- [1 .. n]]
pyt n = [(a, b, c) | a <- [1 .. n], b <- [1 .. n], c <- [1 .. n], a * a + b * b == c * c]
sk xs ys = sum [x * y | (x, y) <- zip xs ys]
re n x = [x | _ <- [1 .. n]]
primes n = []
