package inf112.gfx;

public enum Sprite {
    NONE, TEST,

    STRIKE_CARD, STUN_CARD, SHIELD_CARD, LECTURE_CARD, SKIP_LECTURE_CARD, READ_CARD, ENERGY_DRINK_CARD, BEER_CARD, PROCRASTINATION_CARD, TIKTOK_BREAK_CARD, WAFFLE_THURSDAY_CARD, PIZZA_CARD, RUN_TEST_CARD, SICK_CARD, BUNKER_CARD, COFFEE_BREAK_CARD, STIPEND_CARD, GUN_CARD, RAGE_CARD, NO_SIGNAL_CARD,

    STRIKE_BG, STUN_BG, SHIELD_BG, LECTURE_BG, SKIP_LECTURE_BG, READ_BG, ENERGY_DRINK_BG, BEER_BG, PROCRASTINATION_BG, TIKTOK_BREAK_BG, WAFFLE_THURSDAY_BG, PIZZA_BG, RUN_TEST_BG, SICK_BG, BUNKER_BG, COFFEE_BREAK_BG, STIPEND_BG, GUN_BG, RAGE_BG, NO_SIGNAL_BG,

    END_TURN_BUTTON, ATTACK_ICON, BUFF_ICON, SHIELD_ICON, UNKNOWN_ICON, DEBUFF_ICON,

    ENEMY,

    ATTACKER_ENEMY, PARTY_ENEMY, EXPHIL_ENEMY, EDUROAM_ENEMY, DRUNK_ENEMY, POLICE_ENEMY,

    ENERGY,

    COIN,

    NUM_0, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7, NUM_8, NUM_9,

    BG_0, BG_1, BG_2, BG_REST,

    MAP_COMBAT, MAP_SHOP, MAP_REST, MAP_BOSS, MAP_DOT, MAP_START, MAP_CARDS,

    BATTLE, BOSS, SHOP, REST, TREASURE, START, LOCKED_NODE,

    CARD_COST_0, CARD_COST_1, CARD_COST_2, CARD_COST_3, CARD_COST_4, CARD_TYPE_ATTACK, CARD_TYPE_DEFEND, CARD_TYPE_STATUS,
}
